use std::ffi::c_void;

pub use xross_macros::{XrossClass, xross_class, xross_methods};

/// A standard result structure for FFI calls.
/// Used to pass success/failure status and a pointer to the result or error message.
#[repr(C)]
pub struct XrossResult {
    /// True if the operation was successful.
    pub is_ok: bool,
    /// Pointer to the result data or an error message.
    pub ptr: *mut c_void,
}

/// A marker trait for types that can be bridged between Rust and JVM.
/// Implementation is typically generated by the `xross_class` or `XrossClass` macros.
pub trait XrossClass {
    /// Returns the JSON metadata for the type.
    fn xross_layout() -> String;
}

/// Frees a string allocated by Rust that was passed to the JVM.
///
/// # Safety
///
/// This function is unsafe because it takes a raw pointer and deallocates it.
/// The pointer must have been created by `CString::into_raw`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn xross_free_string(ptr: *mut std::ffi::c_char) {
    if !ptr.is_null() {
        unsafe {
            let _ = std::ffi::CString::from_raw(ptr);
        }
    }
}
