/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.3.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    `maven-publish`
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.serialization)
    kotlin("jvm") version "2.3.10"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation(libs.kotlinpoet)
    implementation(libs.kotlinx.serialization.json)
    implementation(kotlin("stdlib-jdk8"))
}

gradlePlugin {
    // Define the plugin
    val xross by plugins.creating {
        id = "org.xross"
        implementationClass = "org.xross.XrossPlugin"
    }
}

// Add a source set for the functional test suite
val functionalTestSourceSet: SourceSet = sourceSets.create("functionalTest") {
}

configurations["functionalTestImplementation"].extendsFrom(configurations["testImplementation"])
configurations["functionalTestRuntimeOnly"].extendsFrom(configurations["testRuntimeOnly"])

// Add a task to run the functional tests
val functionalTest by tasks.registering(Test::class) {
    testClassesDirs = functionalTestSourceSet.output.classesDirs
    classpath = functionalTestSourceSet.runtimeClasspath
    useJUnitPlatform()
}

gradlePlugin.testSourceSets.add(functionalTestSourceSet)

tasks.named<Task>("check") {
    // Run the functional tests as part of `check`
    dependsOn(functionalTest)
}

tasks.named<Test>("test") {
    // Use JUnit Jupiter for unit tests.
    useJUnitPlatform()
}

tasks.withType<Test>().configureEach {
    // Project Panama を使用するための JVM 引数
    jvmArgs("--enable-native-access=ALL-UNNAMED")

    // Java 25 以上を使用していることを確認
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(25))
    })
}

// XrossPlugin.kt 内の apply メソッドに追加する例
project.tasks.withType(Test::class.java).configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

project.tasks.withType(JavaExec::class.java).configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}
group = "org.xross"
version = "1.0.0"
kotlin {
    jvmToolchain(25)
}